[ingestor]
  [ingestor.service]
  name = "ingestor-service"
  version = "0.0.1"

  [ingestor.storage]
    [ingestor.storage.clickhouse]
    address = "clickhouse"
    port = "9000"
    username = "streamly"
    database = "streamly_analytics"
    password = "dev_clickhouse_123"
    read_timeout = 3600
    write_timeout = 3600

    [ingestor.storage.database]

  [ingestor.redis]
  addr = "redis:6379"
  password = ""

  [ingestor.logging]
  level = "info"
  format = "json"

  [ingestor.http]
  port = 8091
  read_timeout = 3600
  write_timeout = 3600

  [ingestor.component]
  batch_size = 4096
  flush_timeout = 3600
  workers_count = 10

[query]
  [query.service]
  name = "query-service"
  version = "0.0.1"

  [query.storage]
    [query.storage.clickhouse]
    address = "clickhouse"
    port = "9000"
    username = "streamly"
    database = "streamly_analytics"
    password = "dev_clickhouse_123"
    read_timeout = 3600
    write_timeout = 3600

    [query.storage.database]

  [query.redis]
  addr = "redis:6379"
  password = ""

  [query.logging]
  level = "info"
  format = "json"

  [query.http]
  port = 8092
  read_timeout = 3600
  write_timeout = 3600

[auth]
  [auth.service]
  name = "auth-service"
  version = "0.0.1"

  [auth.http]
  port = 8093
  read_timeout = 3600
  write_timeout = 3600

  [auth.storage]
    [auth.storage.database]
    host = "postgres"
    port = "5432"
    user = "streamly"
    password = "dev_password_123"
    database = "streamly_dev"

    [auth.storage.cache]
    host = "redis"
    port = 6379
    user = "root"
    password = "password"
    database = "0"

  [auth.transport]
    host = "rabbitmq"
    port = 5672
    user = "root"
    password = "password"

  [auth.logging]
  level = "debug"
  format = "json"

[platform]
  [platform.service]
  name = "platform-service"

  [platform.http]
  port = 8094
  read_timeout = 3600
  write_timeout = 3600

  [platform.storage]
    [platform.storage.database]
    host = "postgres"
    port = 5432
    user = "streamly"
    password = "dev_password_123"
    name = "streamly_dev"
