Log:
  Level: 'info'

ExternalSecure: false
ExternalDomain: 'zitadel'
ExternalPort: 8080

Database:
  postgres:
    Port: 5432
    Host: 'postgres'
    Database: 'streamly_dev'
    User:
      Username: 'streamly'
      Password: 'dev_password_123'
      SSL:
        Mode: 'disable'
    Admin:
      Username: 'streamly'
      Password: 'dev_password_123'
      SSL:
        Mode: 'disable'
